import apluggy as pluggy
from typing import Dict, Any
from lyikpluginmanager import (
    getProjectName,
    ApplicationDetailSpec,
    ContextModel,
    VerifyHandlerResponseModel,
    VERIFY_RESPONSE_STATUS,
)
import asyncio
from datetime import datetime

impl = pluggy.HookimplMarker(getProjectName())


class ApplicationDetails(ApplicationDetailSpec):
    """
    This will verify the application detail values with the default values
    """

    @impl
    async def verify_handler(
        self, context: ContextModel, payload: Dict[str, Any]
    ) -> VerifyHandlerResponseModel:

        fileds_def: Dict[str, Any] = context.field_definition

        return _compare_defaults_with_payload(field_def=fileds_def, payload=payload)


def _compare_defaults_with_payload(
    field_def: Dict[str, Any], payload: Dict[str, Any]
) -> VerifyHandlerResponseModel:

    _default = _find_defaults_field(field_def=field_def)
    try:
        options_defaults = _default["options"]
        for key, default_value in options_defaults.items():
            payload_value = payload.get(key) or next(
                (
                    v.get(key)
                    for v in payload.values()
                    if isinstance(v, dict) and key in v
                ),
                None,
            )
            if payload_value is not None:
                if float(default_value) <= float(payload_value):
                    pass
                else:
                    return VerifyHandlerResponseModel(
                        status=VERIFY_RESPONSE_STATUS.FAILURE,
                        actor="system",
                        message=f"Value for {key} is not in desired range {default_value}",
                    )
            else:
                print(f"Key '{key}' not found in payload.")
    except Exception as e:
        return VerifyHandlerResponseModel(
            status=VERIFY_RESPONSE_STATUS.FAILURE, actor="system", message=str(e)
        )
    return VerifyHandlerResponseModel(
        status=VERIFY_RESPONSE_STATUS.SUCCESS,
        actor="system",
        message=f"Verified by the system on {datetime.now()}",
    )


def _find_defaults_field(field_def: Dict[str, Any]) -> Dict[str, Any]:
    if field_def.get("derived_field_name") == "_defaults":
        return field_def
    for field in field_def.get("fields", []):
        result = _find_defaults_field(field)
        if result:
            return result
    return None


# Example usage:
payload = {
    "kyc_digilocker": "",
    "card": {"application_type": "", "residential_status": "", "no_of_holders": ""},
    "cash_fut_como_card": {"cash_minimum_paisa": "3", "cash_in_percentage": "2"},
    "cash_jobbing_card": {
        "cash_jobbing_minimum_paisa": "7",
        "cash_jobbing_in_percentage": "3",
    },
    "futures_card": {"futures_minimum_paisa": "9", "futures_in_percentage": "2"},
    "options_card": {"options_standard_rate": "102"},
    "currency_futures_card": {
        "currency_futures_minimum_paisa": "10",
        "currency_futures_in_percentage": "2",
    },
    "currency_options_card": {"currency_options_rate": "30"},
    "commodity_futures_card": {
        "commodity_futures_minimum_paisa": "7",
        "commodity_futures_in_percentage": "1",
    },
    "commodity_options_card": {"commodity_options_rate": "123"},
    "slb_card": {"slb_rate": "45"},
    "flat_per_order_card": {"flat_per_order_rate": ""},
    "online_exe_card": {"online_exe": ""},
}
field_def = {
    "category": "GENERAL",
    "derived_field_name": "application_details",
    "description": None,
    "display_type": "info_pane",
    "field_name": "application_details",
    "field_notation": "",
    "field_type": 256,
    "default_value": None,
    "fields": [
        {
            "category": "GENERAL",
            "derived_field_name": "kyc_digilocker",
            "description": None,
            "display_type": "radiobutton",
            "field_name": "kyc_digilocker",
            "field_notation": "",
            "field_type": 1,
            "default_value": None,
            "fields": [],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {"Yes": "Yes", "NO": "No"},
            "sequence": 10015,
            "title": "Would the client like to complete KYC using Digilocker?",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "card",
            "description": None,
            "display_type": "card",
            "field_name": "card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10017,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "application_type",
                    "description": "Select Option",
                    "display_type": "dropdown",
                    "field_name": "application_type",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {
                        "Trading": "Trading",
                        "DP": "DP",
                        "Trading and DP": "Trading and DP",
                    },
                    "sequence": 10018,
                    "title": "Type of Application",
                    "type": None,
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "residential_status",
                    "description": "Select Option",
                    "display_type": "dropdown",
                    "field_name": "residential_status",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {"Resident": "RESIDENT", "Non-Resident": "NON-RESIDENT"},
                    "sequence": 10019,
                    "title": "Residential Status of Client",
                    "type": None,
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_1",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_1",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10020,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "no_of_holders",
                    "description": "Select Option",
                    "display_type": "dropdown",
                    "field_name": "no_of_holders",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {"One": 1, "Two": 2, "Three": 3},
                    "sequence": 10021,
                    "title": "Number of Holders",
                    "type": None,
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10016,
            "title": "General",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "display_field",
            "description": "TARIFF SHEET",
            "display_type": "display_field",
            "field_name": "display_field",
            "field_notation": "",
            "field_type": 1,
            "default_value": None,
            "fields": [],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10022,
            "title": "",
            "type": "string",
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "segment_rates",
            "description": None,
            "display_type": "card",
            "field_name": "segment_rates",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_2",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_2",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10024,
                    "title": "Segment",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_3",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_3",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10025,
                    "title": "Rates",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10023,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "cash_fut_como_card",
            "description": None,
            "display_type": "card",
            "field_name": "cash_fut_como_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_4",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_4",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10027,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "cash_fut_como",
                    "description": "Cash/ &Future/ Commodity Delivery",
                    "display_type": "display_field",
                    "field_name": "cash_fut_como",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10028,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_5",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_5",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10029,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "cash_minimum_paisa",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "cash_minimum_paisa",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10030,
                    "title": "Minimum Paisa",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_6",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_6",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10031,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "cash_in_percentage",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "cash_in_percentage",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10032,
                    "title": "In %",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10026,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "cash_jobbing_card",
            "description": None,
            "display_type": "card",
            "field_name": "cash_jobbing_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_7",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_7",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10034,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_1",
                    "description": "Cash Jobbing",
                    "display_type": "display_field",
                    "field_name": "display_field_1",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10035,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_8",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_8",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10036,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "cash_jobbing_minimum_paisa",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "cash_jobbing_minimum_paisa",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10037,
                    "title": "Minimum Paisa",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_9",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_9",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10038,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "cash_jobbing_in_percentage",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "cash_jobbing_in_percentage",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10039,
                    "title": "In %",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10033,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "futures_card",
            "description": None,
            "display_type": "card",
            "field_name": "futures_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_10",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_10",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10041,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_2",
                    "description": "Futures",
                    "display_type": "display_field",
                    "field_name": "display_field_2",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10042,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_11",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_11",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10043,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "futures_minimum_paisa",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "futures_minimum_paisa",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10044,
                    "title": "Minimum Paisa",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_12",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_12",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10045,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "futures_in_percentage",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "futures_in_percentage",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10046,
                    "title": "In %",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10040,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "options_card",
            "description": None,
            "display_type": "card",
            "field_name": "options_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_13",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_13",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10048,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_3",
                    "description": "Options",
                    "display_type": "display_field",
                    "field_name": "display_field_3",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10049,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_14",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_14",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10050,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "options_standard_rate",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "options_standard_rate",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10051,
                    "title": "Standard Rate (Rs)",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_15",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_15",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10052,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10047,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "currency_futures_card",
            "description": None,
            "display_type": "card",
            "field_name": "currency_futures_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_16",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_16",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10054,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_4",
                    "description": "Currency Futures",
                    "display_type": "display_field",
                    "field_name": "display_field_4",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10055,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_17",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_17",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10056,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "currency_futures_minimum_paisa",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "currency_futures_minimum_paisa",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10057,
                    "title": "Minimum Paisa",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_18",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_18",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10058,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "currency_futures_in_percentage",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "currency_futures_in_percentage",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10059,
                    "title": "In %",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10053,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "currency_options_card",
            "description": None,
            "display_type": "card",
            "field_name": "currency_options_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_19",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_19",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10061,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_5",
                    "description": "Currency Options",
                    "display_type": "display_field",
                    "field_name": "display_field_5",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10062,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_20",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_20",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10063,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "currency_options_rate",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "currency_options_rate",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10064,
                    "title": "Rate (Rs)",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_21",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_21",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10065,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10060,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "commodity_futures_card",
            "description": None,
            "display_type": "card",
            "field_name": "commodity_futures_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_22",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_22",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10067,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_6",
                    "description": "Commodity Futures",
                    "display_type": "display_field",
                    "field_name": "display_field_6",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10068,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_23",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_23",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10069,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "commodity_futures_minimum_paisa",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "commodity_futures_minimum_paisa",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10070,
                    "title": "Minimum Paisa",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_24",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_24",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10071,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "commodity_futures_in_percentage",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "commodity_futures_in_percentage",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10072,
                    "title": "In %",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10066,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "commodity_options_card",
            "description": None,
            "display_type": "card",
            "field_name": "commodity_options_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_25",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_25",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10074,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_7",
                    "description": "Commodity Options",
                    "display_type": "display_field",
                    "field_name": "display_field_7",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10075,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_26",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_26",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10076,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "commodity_options_rate",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "commodity_options_rate",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10077,
                    "title": "Rate (Rs)",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_27",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_27",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10078,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10073,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "slb_card",
            "description": None,
            "display_type": "card",
            "field_name": "slb_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_28",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_28",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10080,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_8",
                    "description": "SLB",
                    "display_type": "display_field",
                    "field_name": "display_field_8",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10081,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_29",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_29",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10082,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "slb_rate",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "slb_rate",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10083,
                    "title": "Rate (Rs)",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_30",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_30",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10084,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10079,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "flat_per_order_card",
            "description": None,
            "display_type": "card",
            "field_name": "flat_per_order_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_31",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_31",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10086,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "display_field_9",
                    "description": "Flat Per Order",
                    "display_type": "display_field",
                    "field_name": "display_field_9",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10087,
                    "title": "",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_32",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_32",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10088,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "flat_per_order_rate",
                    "description": None,
                    "display_type": "textbox",
                    "field_name": "flat_per_order_rate",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10089,
                    "title": "Rate (Rs)",
                    "type": "string",
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                },
                {
                    "category": "GENERAL",
                    "derived_field_name": "column_break_33",
                    "description": None,
                    "display_type": "column_break",
                    "field_name": "column_break_33",
                    "field_notation": "",
                    "field_type": 4,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {},
                    "sequence": 10090,
                    "title": "",
                    "type": None,
                    "editable": None,
                    "hidden": "",
                    "meta": None,
                },
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10085,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "online_exe_card",
            "description": None,
            "display_type": "card",
            "field_name": "online_exe_card",
            "field_notation": "",
            "field_type": 256,
            "default_value": None,
            "fields": [
                {
                    "category": "GENERAL",
                    "derived_field_name": "online_exe",
                    "description": None,
                    "display_type": "radiobutton",
                    "field_name": "online_exe",
                    "field_notation": "",
                    "field_type": 1,
                    "default_value": None,
                    "fields": [],
                    "format": None,
                    "input_type": None,
                    "locale": "IN",
                    "mandatory": False,
                    "options": {"Yes": "Yes", "NO": "No"},
                    "sequence": 10092,
                    "title": "Online EXE (Fee.Rs.750/",
                    "type": None,
                    "editable": True,
                    "hidden": False,
                    "meta": None,
                }
            ],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {},
            "sequence": 10091,
            "title": "",
            "type": None,
            "editable": True,
            "hidden": False,
            "meta": None,
        },
        {
            "category": "GENERAL",
            "derived_field_name": "_defaults",
            "description": None,
            "display_type": "section_break",
            "field_name": "online_exe",
            "field_notation": "",
            "field_type": 1,
            "default_value": None,
            "fields": [],
            "format": None,
            "input_type": None,
            "locale": "IN",
            "mandatory": False,
            "options": {
                "cash_minimum_paisa": 5,
                "cash_in_percentage": 0.5,
                "cash_jobbing_minimum_paisa": 5,
                "cash_jobbing_in_percentage": 0.5,
                "futures_minimum_paisa": 5,
                "futures_in_percentage": 0.5,
                "options_standard_rate": 100,
                "currency_futures_minimum_paisa": 5,
                "currency_futures_in_percentage": 0.1,
                "currency_options_rate": 20,
                "commodity_futures_minimum_paisa": 5,
                "commodity_futures_in_percentage": 0.03,
                "commodity_options_rate": 100,
                "slb_rate": 20,
            },
            "sequence": 10092,
            "title": "Defaults",
            "type": None,
            "editable": True,
            "hidden": True,
            "meta": None,
        },
    ],
    "format": None,
    "input_type": None,
    "locale": "IN",
    "mandatory": False,
    "options": {},
    "sequence": 10014,
    "title": "Application Details",
    "type": None,
    "editable": True,
    "hidden": False,
    "meta": {"mandatory": "False", "hidden": None, "editable": None},
}


retData = asyncio.run(
    ApplicationDetails().verify_handler(
        context=ContextModel(field_definition=field_def), payload=payload
    )
)

print(retData)
