server:
  http_listen_port: 3101

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: lyikapi
  static_configs:
  - targets:
    - localhost
    labels:
      job: lyik_api
      __path__: /promtail/logs/*.log